server:
  port: 8012

paytm.payment:
  sandbox:
    merchantId: IrinaH93005971299457
    merchantKey: MZLFDNS4DcOg3iCn
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    paytmStatusUrl:  https://securegw-stage.paytm.in/order/status
    callbackUrl: http://localhost:8012/pgresponse
    details:
      MID: ${paytm.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytm.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industrytypeid}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}
spring:
  application:
    name: guesture-payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/
