server:
  port: 8007
  servlet:
    session:
      cookie:
        name: REACHWELLSESSION

security:
  oauth2:
    client:
      client-id: 21e43c55-28ef-478a-ae65-dc896e5eaa34
      client-secret: P@ssw0rd
      user-authorization-uri: http://134.209.154.228:8005/oauth/authorize
      access-token-uri: http://134.209.154.228:8005/oauth/token
    resource:
      token-info-uri: http://134.209.154.228:8005/oauth/check_token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://134.209.154.228:8001/eureka/


spring:
  application:
    name: reachwell-application