server:
  port: 8007
  servlet:
    session:
      cookie:
        name: CARMELSESSION

security:
  oauth2:
    client:
      client-id: pete
      client-secret: P@ssw0rd
      user-authorization-uri: http://139.59.32.238:8005/oauth/authorize
      access-token-uri: http://139.59.32.238:8005/oauth/token
    resource:
      token-info-uri: http://139.59.32.238:8005/oauth/check_token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/


spring:
  application:
    name: common-web-dev