server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://139.59.32.238:3306/spring_dev?createDatabaseIfNotExist=true&useSSL=false
    username: jacksparrow
    password: TH_12rthahalli
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://68.183.246.143:3306/guestjini?createDatabaseIfNotExist=true&useSSL=false
#    username: jacksparrow
#    password: c@rmel@p1rat3s@hub11
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql
  application:
    name: guest-jini-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: prasanna.pete@carmelsolutions.net
    password: TH_13rthahalli
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

logging:
  level:
    root: info
    org:
      hibernate:
        type: info
        SQL: info
    com:
      carmel:
        guestjini:
          helpdesk: info
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file:
    path: 'logs/'
    max-size: 5MB
    clean-history-on-start: false
    name: '/var/log/carmel/guesture-accounts-service.log'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://68.183.246.143:8001/eureka/
      defaultZone: http://139.59.32.238:8001/eureka/

security:
  oauth2:
    resource:
#      token-info-uri: http://68.183.246.143:8000/auth/oauth/check_token
      token-info-uri: http://139.59.32.238:8000/auth/oauth/check_token
    client:
      client-id: 21e43c55-28ef-478a-ae65-dc896e5eaa34
      client-secret: P@ssw0rd
carmel:
  ticketAgents: 'chitrav@shanders.com,kariappa@guesture.in,nanjappa@guesture.in,prasanna.pete@gmail.com'
  baseUrl: http://localhost:8100
  imageSavePath: /opt/carmel/storage/images/
  userInfoURL: http://common-db-service/user/me
  dbServiceURL: http://common-db-service
  accountsServiceURL: http://guesture-accounts-service
  bookingServiceURL: http://guesture-booking-service
  helpdeskServiceURL: http://guesture-helpdesk-service
  paymentServiceURL: http://guesture-payment-service
  inventoryServiceURL: http://guesture-inventory-service
  packageConstants:
    solo: c2c81dca-029a-4bad-ba22-064de303a2b1
    solo-ab: e08f9c6c-a7a5-4f37-863e-89e46cac460a
    solo-ab-bal: 3f444cb2-e50d-4d77-b36f-437cf31f8560
    buddy-av: 74df04e3-74bc-4df3-bee0-fdf9cf295f61
    buddy-av-ab: acf578d1-ed0e-4f73-b2d8-53ed72cea846
    buddy-av-ab-bal: b838a75f-683a-4d41-bd7e-751bab8c044f
    buddy-dw: db86c15d-0cf6-4863-8d16-0e378cd1d3fb
    buddy-dw-ab: 8dc5bbd8-fdb0-4b8d-a98a-82a9377b2441
    buddy-dw-ab-bal: 6040edcf-a768-4bb7-aa56-d7157325c496
    trio: a6ea4896-1323-4d54-9968-73778f64be80
    trio-ab: ea3c81c2-e5b4-4a46-8e80-c5056de8e0f5
  propertyConstants:
    av: dd019bb3-be78-48e9-9039-70281031c719
  allowedPropertyTypes:
    pods: 600
    rooms: 500
  oauth2:
    client:
      grantType: client_credentials
      clientId: 21e43c55-28ef-478a-ae65-dc896e5eaa34
      clientSecret: P@ssw0rd
#      accessTokenUri: http://68.183.246.143:8000/auth/oauth/token
      accessTokenUri: http://139.59.32.238:8000/auth/oauth/token

