
server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://139.59.32.238:3306/spring_dev?createDatabaseIfNotExist=true&useSSL=false
    username: jacksparrow
    password: TH_12rthahalli
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql
  application:
    name: guest-jini-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

logging:
  level:
    root: info
    org:
      hibernate:
        type: info
        SQL: info
    com:
      carmel:
        guestjini:
          helpdesk: trace
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file:
    path: 'logs/'
    max-size: 5MB
    clean-history-on-start: false
    name: '/var/log/carmel/guesture-accounts-service.log'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://139.59.32.238:8005/oauth/check_token
    client:
      client-id: 21e43c55-28ef-478a-ae65-dc896e5eaa34
      client-secret: P@ssw0rd
carmel:
  imageSavePath: /opt/carmel/storage/images/
  userInfoURL: http://common-db-service/user/me
  dbServiceURL: http://common-db-service
  accountsServiceURL: http://guesture-accounts-service
  bookingServiceURL: http://guesture-booking-service
  helpdeskServiceURL: http://guesture-helpdesk-service
  paymentServiceURL: http://guesture-payment-service
  inventoryServiceURL: http://guesture-inventory-service
  packageConstants:
    solo: 7ae0a514-b2df-4ae1-8799-947d789a4c2f
    solo2d: d4174b0e-1590-432c-ac94-d36f7cbd5f45