server:
  port: 8006

spring:
#  datasource:
#    url: jdbc:mysql://68.183.246.143:3306/guestjini?createDatabaseIfNotExist=true&useSSL=false
#    username: jacksparrow
#    password: c@rmel@p1rat3s@hub11
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://139.59.32.238:3306/spring_dev?createDatabaseIfNotExist=true&useSSL=false
    username: jacksparrow
    password: TH_12rthahalli
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql
  application:
    name: common-db-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: amazon@carmelsolutions.net
    password: P@ssw0rd
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 150MB
      enabled: true

logging:
  level:
    root: info
    org:
      hibernate:
        type: info
    com:
      carmel:
        common:
          dbservice: info
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file:
    path: 'logs/'
    max-size: 5MB
    clean-history-on-start: false
    name: '/var/log/carmel/common-db-service.log'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://68.183.246.143:8001/eureka/
      defaultZone: http://139.59.32.238:8001/eureka/

security:
  oauth2:
    resource:
#      token-info-uri: http://68.183.246.143:8000/auth/oauth/check_token
      token-info-uri: http://139.59.32.238:8000/auth/oauth/check_token
    client:
      client-id: 21e43c55-28ef-478a-ae65-dc896e5eaa34
      client-secret: P@ssw0rd
carmel:
  fileUploadPath: /Users/pete/SVN/carmel/GuestJini-Development/spring/common-db-service/src/main/resources/uploads/
  userInfoURL: http://common-db-service/user/me
  dbServiceURL: http://common-db-service
  inventoryServiceURL: http://guesture-inventory-service
  imageSavePath: /opt/carmel/storage/images/
  linkedInConfigPath: /Users/pete/SVN/carmel/GuestJini-Development/spring/common-db-service/src/main/resources/linkedin.yml
  facebookConfigPath: /Users/pete/SVN/carmel/GuestJini-Development/spring/common-db-service/src/main/resources/facebook.yml
  instagramConfigPath: /Users/pete/SVN/carmel/GuestJini-Development/spring/common-db-service/src/main/resources/instagram.yml
  twitterConfigPath: /Users/pete/SVN/carmel/GuestJini-Development/spring/common-db-service/src/main/resources/twitter.yml
  googleKey: AIzaSyAnt2NlFuXDQAimRh29sLvag5UrmjaQReo
  OTPGatewayURL: https://2factor.in/API/V1/
  OTPGateWayKey:  b3d3355a-199a-11eb-b380-0200cd936042
  GuestRoleId: 114a95f6-520a-4d0f-bf53-bf4758752d74
  SupportRoleId: 114a95f6-520a-4d0f-bf53-bf4758752d75
