server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:mysql://139.59.50.103:3306/guesture_cupid?createDatabaseIfNotExist=true
    username: jacksparrow
    password: TH_12rthahalli
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: lazaro-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: amazon@carmelsolutions.net
    password: P@ssw0rd
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
logging:
  level:
    root: info
    org:
      springframework:
        web:
          client: trace
    com:
      carmel:
        guesture:
          lazaroservice: trace
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file:
    path: 'logs/'
    max-size: 5MB
    clean-history-on-start: false
    name: 'logs/lazaro-service.log'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/
olive-crm:
  baseUrl: http://localhost:8080
  oauth2:
    client:
      grantType: client_credentials
      clientId: 532edc05-e070-5277-8c19-5d91fa453879
      clientSecret: P@ssw0rd
      accessTokenUri: http://crm.olive-suite.com/Api/access_token
  crmURL: http://crm.olive-suite.com/Api/V8/module
  crmClientId: 532edc05-e070-5277-8c19-5d91fa453879
  crmClientSecrete: P@ssw0rd
  crmAuthURL: http://crm.olive-suite.com/Api/access_token
  leadSyncInterval: 30000
  activitySyncInterval: 40000
  leadMailTo: kariappa@guesture.in, chitra@guesture.in


