server:
  port: 8008

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbcl_spring?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql
  application:
    name: guesture-booking-service
logging:
  level:
    root: info
    org:
      hibernate:
        type: info
        SQL: debug
    com:
      carmel:
        guestjini:
          booking: trace
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file:
    path: 'logs/'
    max-size: 5MB
    clean-history-on-start: false
    name: '/var/log/carmel/guesture-booking-service.log'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://139.59.32.238:8005/oauth/check_token
    client:
      client-id: 21e43c55-28ef-478a-ae65-dc896e5eaa34
      client-secret: P@ssw0rd
carmel:
  userInfoURL: http://common-db-service/user/me
  dbServiceURL: http://common-db-service
  inventoryServiceURL: http://guesture-inventory-service