
server:
  port: 8005
spring:
  datasource:
    url: jdbc:mysql://139.59.32.238:3306/spring_dev?createDatabaseIfNotExist=true&useSSL=false
    username: jacksparrow
    password: TH_12rthahalli
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql
  application:
    name: auth-service
logging:
  level:
    root: info
    org:
      hibernate:
        type: info
      springframework:
        security:
          oauth2: trace
    com:
      carmel:
        common:
          dbservice: trace
          authserver: trace
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file:
    path: 'logs/'
    max-size: 5MB
    clean-history-on-start: false
    name: '/var/log/carmel/auth-service.log'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/