server:
  port: 8000
spring:
  application:
    name: carmel-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://139.59.32.238:8001/eureka/
ribbon:
  eureka:
    enabled: true

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:8005
    common-db-service:
      path: /common/**
      url: http://localhost:8006
    common-web:
      path: /web/**
      url: http://localhost:8007
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 50000000
#    lazaro-service:
#      path: /lazaro/**
#      url: http://localhost:8003
#    common-web:
#      path: /web/**
#      url: http://localhost:8004
